export const groups = {
  '01': 'Technical Literature',
  '02': 'Scopes of Service and repair work (new category)',
  11: 'Engine Mechanical',
  12: 'Engine Electrical',
  13: 'Fuel Injection',
  16: 'Fuel Supply',
  17: 'Cooling System',
  18: 'Exhaust',
  21: 'Clutch',
  22: 'Engine and gearbox suspension',
  23: 'Standard Transmission',
  24: 'Automatic Transmission',
  25: 'Gearshift',
  26: 'Drive Shaft',
  27: 'Transfer case',
  28: 'Dual Clutch Transmission',
  31: 'Front suspension',
  32: 'Steering components',
  33: 'Rear suspension',
  34: 'Braking components',
  35: 'Pedals',
  36: 'Wheels',
  41: 'Bodywork',
  51: 'Vehicle trim',
  52: 'Seats',
  54: 'Sunroof/Convertible top',
  61: 'Body Electrical',
  62: 'Instrument Cluster',
  63: 'Lighting',
  64: 'Climate control',
  65: 'Audio, navigation, and electronic systems',
  66: 'Distance systems and cruise control',
  67: 'Window motors on newer BMW\'s',
  71: 'Equipment parts',
  72: 'Restraint systems',
  82: 'Universal Accessories',
  84: 'Communication systems',
  88: 'BMW specific tools'
};

export const sites = [
  {
    name: 'RealOEM',
    searchUrl: 'https://www.realoem.com/bmw/enUS/partxref?q=',
  },
  {
    name: 'GetBMWParts',
    searchUrl: 'https://www.getbmwparts.com/search?search_str=',
  },
  {
    name: 'FCP Euro',
    searchUrl: 'https://www.fcpeuro.com/products?utf8=%E2%9C%93&keywords=',
  },
  {
    name: 'ECS',
    searchUrl: 'https://www.ecstuning.com/Search/SiteSearch/',
  },
  {
    name: 'BMWPartsPros',
    searchUrl: 'https://bmwpartspros.com/parts/index.cfm?make=BMW&action=oePartSearch&siteid=216857&searchText=',
  },
  {
    name: 'Google',
    searchUrl: 'https://www.google.com/search?q=',
  },
  {
    name: 'Amazon',
    searchUrl: 'https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=',
  },
  {
    name: 'E90Post',
    searchUrl: 'https://www.e90post.com/forums/googlesearch.php?q=',
  },
];
